[common]
    version = "1.0.0"
    env = "local"
    hostPort = "127.0.0.1"
    family = "fliter-service"
    serverName = "fliter-service"

[log]
    dir = "./"

[router]
    [router.indentify]
        [router.indentify.app]
            appkey = "abc"
            appsecret = "abc123"

[mhttp]
    [mhttp.pprof]
        port = 6512
        readTimeout = "1s"
        writeTimeout = "1s" 
    [mhttp.inner]
        port = 6511
        readTimeout = "1s"
        writeTimeout = "1s"
    [mhttp.outter]
        port = 6510
        readTimeout = "100s"
        writeTimeout = "100s"
        
[mysql]
    [mysql.master]
        addr = "127.0.0.1"
        dsn = "root:xiangfeifei@tcp(127.0.0.1)/filter?timeout=5s&readTimeout=5s&writeTimeout=5s&parseTime=true&loc=Local&charset=utf8,utf8mb4"
        active = 2
        idle = 2
[time]
    tick ="5s"